
'use strict';

export class ActorDialog {
  constructor(
    actor,
    options = {
      idle: false,
    },
  ) {

    this.#_actor = actor;

    if (options.idle) {
      this.#_timer = setInterval(this.#_idle_function, 15000);
    }

  }

  #_actor;
  #_timer;

  #_idle_function = () => {
    const actor = this.#_actor;

    if (actor.speech) {
      actor.speech = null;
      return;
    }

    actor.speech = RANDOM_IDLE_DIALOG[
      Math.floor(Math.random() * RANDOM_IDLE_DIALOG.length)
    ];
  };

  dispose = () => {
    if (this.#_timer != null) {
      clearInterval(this.#_timer);
    }
  };
}

const RANDOM_IDLE_DIALOG = [
  'I 🐳 always love you.',
  'I’d love to cook you dinner. You know, if I knew how to cook. How do you feel about microwave burritos?',
  'I smile whenever I get a message from you 😊',
  'I promise to always be on your side. (You know, unless I’m under you, or on top, or we’re trying something weird and diagonal.) 😜',
  'You are amazing and perfect in every way. Damn, autocorrect. I mean good morning.',
  'I could totally go for some of you right now.',
  'Man, my cheeks hurt. I need to stop smiling so much, but I can’t stop. This is all your fault.',
  'Things I want right now: 1. You 2. I forget. Oh ya, you.',
  'I like you a lot. Like, a lot a lot.',
  'If I choose texting you over sleep, you must be pretty special.',
  'Never forget, I love you now and forever!',
  'I’ve been thinking about you all day. Can’t wait to see you later!',
  'Morning, love! Hope you’re having a good day 😊',
  'Hello beautiful 😍 Hope your day is as amazing as you are!',
  'In case you forgot, just a reminder that I love you 😘',
  'I was just looking through your Instagram and dang baby, you look good 😎',
  'It’s driving me crazy that I have to wait until tonight to see you!',
  'I’m thinking about you. That is all 🤗',
  'I’d like to spoil you this weekend. What do you say we do a little shopping with my credit card?',
  'I am one lucky man to have a woman like you!',
  'My life has been brighter ever since we met.',
  'Been missing you like crazy… When can I see you next?',
  'Any plans tonight? I was thinking I could cook for you 🍳',
  'Out of all the 🐠 in the sea, you are most definitely the one for me.',
  'Even when I’m having a bad day, whenever I see your face I instantly feel better.',
  'How did I get so lucky to end up with a woman like you?',
  'I must’ve been a saint in my past life… I’m so lucky to be with you!',
  'What’s one thing you’ve always wanted to do? Let’s do it this weekend 😃',
  'Good morning! Hope you slept well.',
  'Literally can’t stop thinking about how amazing you are 😊',
  'I don’t think I’ve stopped smiling since we’ve met.',
  'All my friends are jealous that I’ve ended up with a woman as wonderful as you.',
  'They say when you meet that special someone you just know. The first time I saw you that was it. I knew you were the one for me.',
  'Roses are red, violets are blue, I love you so much and I hope you feel the same way too!',
  'Movie and popcorn tonight? It’s on me! 🎥🍿',
  'What’s your favorite kind of candy? Just wondering… it’s not like I’m at the store and about to get it for you 🍫',
  'Are you busy during your lunch break today? I thought I could swing by and take you out.',
  'Last night was so amazing. Just wanted to let you know how I felt 😊',
  'I can’t wait to see you later! Been looking forward to this all day.',
  'Sometimes I ask myself, “Wow, how did I get so lucky to end up with her?”… I still don’t know! But I’m sure glad I did 😉',
  'I can’t wait to marry you someday.',
  'Fact: You are the best wife ever 🙌',
  'I couldn’t imagine a better person to raise a family with.',
  'I now understand why it never worked out with anyone else. I was supposed to find and end up with you ❤️',
  'Are your legs tired, because you’ve been running through my mind all day! 🏃',
  'I’m so excited to see what our future holds.',
  'You are so beautiful. Never doubt that.',
  'I’m going to marry you one day. Mark my words. 😉',
  'I’m sorry you’re not having a good day. Is there anything I can do to make it better?',
  'How about we open up that nice bottle of wine tonight?',
  'I’d love to send your mother some flowers (just because she raised such a wonderful daughter!). What’s her address?',
  'I know you’ve had a rough day and I will do whatever I can to make it better. I love you!',
  'What do you think about having a spontaneous date night?',
  'You never have anything to worry about with me because YOU are the woman for me!',
  'I love your eyes, I just start drowning in them.',
  'I love the way that you giggle whenever I say something silly.',
  'You have the best laugh.',
  'Never change who you are, I love you just the way you are.',
  'I don’t know what my favorite thing about you is. I love every single part of you!',
  'I know it’s only been a few hours since we’ve seen each other, but I can’t stop thinking about you.',
  'Good night love, sweet dreams 😴',
  'Thanks to you I know what true love feels like 💖',
  'I can’t wait to hold you in my arms and give you a big bear hug later!',
  'I’m thinking it’s a pizza and ice cream kind of night. You in? 🙂',
  'What kind of food are you craving right now? I’d love to make it for you!',
  'Want to play hooky today?',
  'You are so beautiful. I am one lucky guy.',
  'I can’t wait to continue to learn more and more about you.',
  'Good morning! I had the best time last night. Can’t wait to see you again!',
  'Good night! Sleep well, can’t wait to see you tomorrow.',
  'Remember when we first met? That was the best day of my life.',
  'When we had our first kiss I knew you were the one.',
  'You awake? Can’t stop thinking about you!',
  'When I close my eyes all I can see is you.',
  'Can’t get you off my mind 💭',
  'You looked amazing in that dress last night, by the way 😉',
  'I’ll do whatever I can to support you.',
  'I want to be your rock you can lean on.',
  'Every day I wake up and thank God that he put you in my life.',
  'I honestly don’t know what I would do without you. I love you so much!',
  'The world is a scary place to live in right now, but being by your side makes it all worth it.',
  'Let’s watch a movie tonight. Your pick 😄',
  'I love you to the moon and back.',
  'I’m sorry we fought last night. I was in the wrong. I love you so much.',
  'Hi sweetie, thinking of you!',
  'I love how natural we are together. We were meant to be together.',
  'I can’t imagine my life without you. You really are my shining star 🌟',
  'My favorite thing about you is your kindness.',
  'You are really special, you know that, right?',
  'Oh the things I would do to see you right now!',
  'You don’t need to get all dolled up around me. I love you just the way you are.',
  'I love that you challenge me. I feel I’m a better person ever since you came into my life.',
  'I love how strong and determined you are.',
  'Being with you makes me a better man.',
  'Just heard our song and it made me think of you 🎶',
  'Not only are you my girlfriend, you’re also my best friend.',
  'Every morning I get to wake up next to you is the best morning ever.',
  'I love waking up next to you.',
  'I love that you’re the first thing I see when I wake up and the last thing I see when I go to sleep.',
  'If I could I would spend every waking minute with you.',
  'Not only do I love you, but I also love your family.',
  'You’re mine, and I’m yours. We were meant to be 💕',
  'I’ll support you in whatever you want to do.',
  'I can’t stop smiling. I had so much fun last night.',
  'I think you’re a real 🍕work!',
  'I love you from my head to-ma-toes! 🍅🍅🍅',
  'I find you very appeeling. 🍌😍',
  'I’m 🍌 for you! Let’s never split.',
  'We make a great 🍐',
  'I’m falling so hard for you.',
  'Can I borrow a kiss? I promise I’ll give it back. 😘',
  'All I want to do is cuddle with you right now.',
  'You’re kind of, sort of, basically, always on my mind.',
  'I have a problem… I can’t get enough of you.',
  'I can’t stop smiling. It’s all your fault. 😆',
  'I like it when you smile but I LOVE it when I’m the reason.',
  'I wish you could see the stupid smile I get when we’re texting.',
  'I want to be the reason you look down at your phone and smile.',
  'There will always be room for your hand in mine.',
  'You’re cute. Can I keep you? 🤗',
  'You make me smile. Big time. 😃',
  'When we’re together, I could just lay next to you forever. Or until we decide to go eat.',
  'When I walk into a room full of people, I always look for you first.',
  'I think you’re suffering from a lack of vitamin me.',
  'I like you a lot more than I originally planned.',
  'Let’s commit the perfect crime… I’ll steal your heart and you’ll steal mine.',
  'You make my heart soar 💕',
  'I love you more than pizza. And I really love pizza.',
  'Wanna know what’s on the menu for tonight? Me N U!',
  'I hope your day is as nice as you are!',
  'Did you know rawr is I love you in dinosaur? RAWR!',
  'I’d be 🦁 if I didn’t say I totally love you.',
  'Hi there. Hope you’re feline good today. 😺',
  'You really 💡up my 🌎!',
  'I pawsitively love you. 🐾',
  'I love you ❤️',
  'I’d like to be the air you breathe and the Sun that heats you, but the most I want is to be the love of your life.',
  'Every time you are away from me, I feel loneliness in my heart. I can’t stop missing and loving you. You can’t imagine how much I love you sweetheart, and how much I need you.',
  'You are the owner of my heart, my feelings, my soul and my body. I completely belong to you, baby. I love you.',
  'You are my day and my night, my sky, my Moon, my stars and my Sun. If it were my choice, we would be together all day. Thank you for giving me everything.',
  'When we are together I feel a prisoner of your heart, I feel so happy that I don’t mind that my life depends on you. I don’t want to be free if I am chained to your love.',
  'Loving you is knowing what true love is. There is no logical explanation for my feelings. My heart only responds to yours. You are the love of my life.',
  'Love and being loved is the best feeling I ever felt. It is beautiful, crazy, unexpected and even magical. Thank you for loving me as much as I love you.',
  'I love so many things about you that I don’t even know where to start. I like everything about you: I think you were made for me and I was made for you.',
  'I never imagined how love could be until I met you. The only thing that really matters is to be together forever. I love you till the end of times.',
  'Our friendship was the best preamble for our love story. I’ll never forget the day I met you, and I will always remember the day I loved you.',
  'I love you because with you I don’t feel alone on Sundays and my Mondays are not that bad. You make my week, my month, my year and my life!',
  'Love makes no sense if it is not to the right person. I feel very lucky to be with you!',
  'If you feel alone, I will be your shadow. If you want to cry, I will be your shoulder. If you are sad, I will be your smile. Every time you need me, I will be there.',
  'You can’t imagine how much I love you! You are the girl that every man desires. I know I can count on you, as you can count on me. I want to spend my life with you.',
  'I admire you, I care for you, I love you, I respect you and I trust you. Unconditionally.',
  'Life is too short to keep your feelings for yourself. I cannot hide these words in my heart anymore because they are hurting me: I LOVE YOU.',
  'I knew, from the first time, that I would love you forever. Your smile made me fall in love with you, and from that moment I knew I wanted to see that smile every morning.',
  'I wish you two things: everything and nothing. Everything that makes you happy and nothing that makes you suffer. I love you!',
  'You are like those songs that I can’t keep out of my mind. And it is not because you are in my head, but also in my heart.',
  'I don’t want you to be perfect. I love your imperfections because they make my life as perfect as one can imagine.',
  'I stopped believing in love, but after seeing your smile I became a believer again. I love you, I think of you, I miss you.',
  'You are and always be the prettiest girl in the world. At least in my world. Because YOU are my world. And not only that: you are my whole universe!',
  'With just one call, one text, one glance or one smile, you make my day. Be aware that you are the most important person in my life and it doesn’t matter where I am, I am always thinking about you. Day and night.',
  'You are the most wonderful love I ever had. With you, I feel untouchable, invincible. You make me stronger, happier and wiser. Because not everybody knows what is love.',
  'It’s good to know that when I go back home you will be there, smiling and waiting for me. I think of you all day long and I don’t know what I would do without you.',
  'Excuse me, I just want to tell you that I want to protect you, steal your smiles, stop your tears and wake up by your side. You are the most wonderful thing that ever happened to me.',
  'You can keep my heart but bring me back to life with your kisses.',
  'The world is so small compared to my love for you…',
  'My favorite place is by your side.',
  'When you are next to me, every little thing seems wonderful!',
  'You made me love you, now I am your responsibility.',
  'I would invent you if you didn’t exist!',
  'If you say “I love you”, I will give you my whole life.',
  'I found my princess, would you let me be your prince?',
  'Having you next to me is the only thing I need to be happy.',
  'I came to steal you a million kisses!',
  'You are my daily motivation, only you can guide me through the path of life. I know that our relationship will last forever because true love never ends.',
  'You are my sweet treasure, and only with your presence, you make me the happiest man on Earth. I will be devoted to you the rest of my life.',
  'It didn’t take a long time to know that I was in love with you. I hope we can be together for the rest of our lives.',
  'Don’t ever worry about the future of our relationship: you will be my queen forever and I will be your king if you let me.',
  'I fall in love with you every day, every time you look at me, every time you smile and every time you say “I love you”.',
  'The little things you give me to fulfill my life: a little smile, a little kiss, a little glance. I don’t need anything else to be happy.',
  'Thank you for painting my life with the colors of happiness: you make me feel lucky, loved, happy and special. Thank you for giving me so much joy. I love you forever.',
  'I love you not only for your beauty but for your soul. Our love will be alive forever because I love the way you are.',
  'You have become more than just a friend or just a lover: you are my soulmate, the reason for my happiness and the person with whom I want to share my life. I love you.',
  'You feed my heart and my soul with your love. I love you more than anything in this world!',
];
